<a href="https://colab.research.google.com/github/chrisdaudier/pytorch-deep-learning/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(f"Torch version: {torch.__version__}")



Torch version: 2.6.0+cu124


# Introduction to Tensors

## Creating Tensors

PyTorch Tensors are created using `torch.Tensor()` = https://pytorch.org/docs/stable/tensors.html

In [2]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
# get scalar back as Python int
scalar.item()

7

In [11]:
# Vector
vector = torch.tensor([7, 7, 7])
vector

tensor([7, 7, 7])

In [12]:
vector.ndim

1

In [13]:
vector.shape

torch.Size([3])

In [14]:
# Matrix
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [15]:
MATRIX.ndim

2

In [16]:
MATRIX.shape

torch.Size([2, 2])

In [17]:
MATRIX[1]

tensor([ 9, 10])

In [18]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [19]:
TENSOR.ndim

3

In [20]:
TENSOR.shape

torch.Size([1, 3, 3])

In [21]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [22]:
TENSOR[0][1]

tensor([3, 6, 9])

In [23]:
# prompt: define a tensor with a shape of 2 x 4 x 3

my_tensor = torch.arange(2 * 4 * 3).reshape(2, 4, 3)
print(my_tensor)
print(my_tensor.shape)
my_tensor.ndim

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17],
         [18, 19, 20],
         [21, 22, 23]]])
torch.Size([2, 4, 3])


3